channel_id: UCt7fwAhXDy3oNFTAzF2o8Pw
playlists:
  electronic_reviews:
    date: ''
    id: PLP4CSgl7K7ormX2pL9h0inES2Ub630NoL
  hip_hop_reviews:
    date: ''
    id: PLP4CSgl7K7ormBIO138tYonB949PHnNcP
  loud_rock_reviews:
    date: ''
    id: PLP4CSgl7K7orAG2zKtoJKnTt_bAnLwTXo
  not_good:
    date: ''
    id: PLP4CSgl7K7orMz0p3u1uCedytfedxY9IG
  other_reviews:
    date: ''
    id: PLP4CSgl7K7orSnEBkcBRqI5fDgKSs5c8o
  pop_reviews:
    date: ''
    id: PLP4CSgl7K7oqibt_5oDPppWxQ0iaxyyeq
  rock_reviews:
    date: ''
    id: PLP4CSgl7K7ori6-Iz-AWcX561iWCfapt_
